### ISSUE TITLE
"Morph::Runner.go should handle restarting from a stopped container" is brittle

### ISSUE THREAD

**Issue by snoblenet** [openaustralia/morph#971]
Sometimes all tests pass on `bundle exec dotenv rspec`. Sometimes, following the same command, one of the tests will fail, with this explanation:

```
Failures:

  1) Morph::Runner.go should handle restarting from a stopped container
     Failure/Error: expect(logs.join).to eq [
       
       expected: "Injecting configuration and compiling...\nInjecting scraper and running...\nStarted!\n1...\n2...\n"
            got: "Injecting configuration and compiling...\nInjecting scraper and running...\nStarted!\n1...\n2..."
       
       (compared using ==)
       
       Diff:
       
     # ./spec/lib/morph/runner_spec.rb:125:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:83:in `block (3 levels) in <top (required)>'
     # /Users/steven/.rvm/gems/ruby-2.0.0-p353/gems/vcr-2.9.3/lib/vcr.rb:237:in `turned_off'
     # ./spec/spec_helper.rb:81:in `block (2 levels) in <top (required)>'

```
